import { Category, Product } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Phones",
    slug: "phones",
    description: "Brand new smartphones with original manufacturer warranty",
    image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-2",
    name: "Phone Accessories",
    slug: "phone-accessories",
    description: "Covers, screen protectors, and everyday protection",
    image_url: "https://images.unsplash.com/photo-1601593378480-85345684263e?w=600",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-3",
    name: "Chargers & Cables",
    slug: "chargers",
    description: "Fast chargers, original Type-C, Lightning, and adapter plugs",
    image_url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-4",
    name: "Earphones & Audio",
    slug: "audio",
    description: "Wireless earbuds, Bluetooth speakers, and wired headsets",
    image_url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cat-5",
    name: "Power Banks",
    slug: "power-banks",
    description: "High-capacity power packs for non-stop uptime on the go",
    image_url: "https://images.unsplash.com/photo-1609592807984-7548a30680d2?w=600",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Samsung Galaxy A17",
    slug: "samsung-galaxy-a17",
    category_id: "cat-1",
    category_name: "Phones",
    description: "Crisp Super AMOLED display, long-lasting 5000mAh battery, and triple camera setup. Ideal daily driver.",
    price: 650000,
    discount_price: 620000,
    currency: "UGX",
    availability: "IN STOCK",
    is_featured: true,
    is_new_arrival: true,
    is_active: true,
    specifications: {
      "RAM": "6GB",
      "Storage": "128GB",
      "Battery": "5000 mAh",
      "Display": "6.6 inch AMOLED",
    },
    images: [
      {
        id: "img-1",
        product_id: "prod-1",
        image_url: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800",
        r2_key: "products/samsung-a17.jpg",
        alt_text: "Samsung Galaxy A17 Front View",
        sort_order: 0,
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-2",
    name: "Anker 20W Fast Power Adapter",
    slug: "anker-20w-fast-power-adapter",
    category_id: "cat-3",
    category_name: "Chargers & Cables",
    description: "Compact high-speed USB-C wall charger. Charges phones up to 3x faster than standard 5W chargers.",
    price: 85000,
    currency: "UGX",
    availability: "IN STOCK",
    is_featured: true,
    is_new_arrival: false,
    is_active: true,
    specifications: {
      "Output": "20W Power Delivery",
      "Port": "USB-C",
      "Compatibility": "iPhone & Android",
    },
    images: [
      {
        id: "img-2",
        product_id: "prod-2",
        image_url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800",
        r2_key: "products/anker-charger.jpg",
        alt_text: "Anker Fast Charger Plug",
        sort_order: 0,
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-3",
    name: "Oraimo FreePods 4 Noise Cancelling Earbuds",
    slug: "oraimo-freepods-4",
    category_id: "cat-4",
    category_name: "Earphones & Audio",
    description: "Active noise cancellation, rich bass response, and up to 35 hours total playtime with charging case.",
    price: 145000,
    discount_price: 135000,
    currency: "UGX",
    availability: "IN STOCK",
    is_featured: true,
    is_new_arrival: true,
    is_active: true,
    specifications: {
      "Bluetooth": "v5.2",
      "Playtime": "35 Hours",
      "ANC": "Active Noise Cancellation",
    },
    images: [
      {
        id: "img-3",
        product_id: "prod-3",
        image_url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
        r2_key: "products/oraimo-freepods-4.jpg",
        alt_text: "Oraimo FreePods 4 Case and Buds",
        sort_order: 0,
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-4",
    name: "20,000mAh Heavy-Duty Power Bank",
    slug: "20000mah-heavy-duty-power-bank",
    category_id: "cat-5",
    category_name: "Power Banks",
    description: "Charge multiple devices simultaneously. Built-in LED battery percentage readout.",
    price: 120000,
    currency: "UGX",
    availability: "LIMITED STOCK",
    is_featured: false,
    is_new_arrival: false,
    is_active: true,
    specifications: {
      "Capacity": "20,000 mAh",
      "Ports": "2x USB-A, 1x USB-C",
      "Fast Charge": "18W QC 3.0",
    },
    images: [
      {
        id: "img-4",
        product_id: "prod-4",
        image_url: "https://images.unsplash.com/photo-1609592807984-7548a30680d2?w=800",
        r2_key: "products/powerbank-20k.jpg",
        alt_text: "20000mAh Power Bank Matte Black",
        sort_order: 0,
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
